global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ] # Kafka Exporter 的地址和端口
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']